# Generated by Django 6.0.4 on 2026-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
